name: Hello from Environments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  deployment_dev:
    runs-on: ubuntu-latest
    environment: Development
    uses: byrontuckett/actions-environments/.github/workflows/hello-called-workflow.yml@main
  deployment_uat:
    runs-on: ubuntu-latest
    environment: UAT
    uses: byrontuckett/actions-environments/.github/workflows/hello-called-workflow.yml@main