name: Hello from Environments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment_dev:
    uses: byrontuckett/actions-environments/.github/workflows/hello-called-workflow.yml@main
    with:
      ENVIRONMENT: Development
  deployment_uat:
    uses: byrontuckett/actions-environments/.github/workflows/hello-called-workflow.yml@main
    with:
      ENVIRONMENT: UAT