name: Hello from Environments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  gday_dev:
    uses: byrontuckett/actions-environments/.github/workflows/hello-called-workflow.yml@main
    environment: Development
  gday_uat:
    uses: byrontuckett/actions-environments/.github/workflows/hello-called-workflow.yml@main
    environment: UAT