name: Hello ENVs
  
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Print variable
      run: echo "Printed Variable $NAME"
      env:
        NAME: ${{ vars.NAME }}

